name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 8 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 14
          days-before-issue-stale: 90
          days-before-issue-close: 21
          exempt-issue-labels: "knuu"
          start-date: "2024-05-16T00:00:00Z"
